# Dependabot dependency version checks / updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    reviewers:
      - "bestgopher"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    schedule:
      interval: "daily" # 这里添加了 schedule
    directory: "/"
    reviewers:
      - "bestgopher"
    groups:
      deps:
        patterns:
          - "*"
