id = "wakatime"
name = "wakatime"
description = "Wakatime support."
version = "0.1.8"
schema_version = 1
authors = ["bestgopher <84328409@qq.com>"]
repository = "https://github.com/wakatime/zed-wakatime"

[language_servers.wakatime]
name = "wakatime"
languages = [
    "ActionScript",
    "Ada",
    "Agda",
    "Aiken",
    "Amber",
    "Ansible",
    "AsciiDoc",
    "Assembly",
    "Astro",
    "AWK",
    "Shell Script",
    "Beancount",
    "Bend",
    "bitbake",
    "Blade",
    "Blueprint",
    "BQN",
    "Brainfuck",
    "C3",
    "Caddyfile",
    "Cadence",
    "Cairo",
    "Cap'n Proto",
    "Cedar",
    "CFEngine",
    "cfhtml",
    "cfml",
    "cfscript",
    "Clojure",
    "COBOL",
    "CONL",
    "Cooklang",
    "Cpp2",
    "Crystal",
    "ECR",
    "CSV",
    "Gherkin",
    "CUE",
    "Curry",
    "Cylc",
    "Cypher",
    "Cython",
    "D",
    "D2",
    "Dafny",
    "Dart",
    "DBML",
    "devicetree",
    "Docker Compose",
    "Dockerfile",
    "DuckyScript",
    "Earthfile",
    "EDI X12",
    "EJS",
    "Elisp",
    "Elm",
    "Handlebars",
    "env",
    "Exograph",
    "Firebase Rules",
    "Fish",
    "FlatBuffers",
    "Fortran",
    "Fountain",
    "FSharp",
    "GDScript",
    "Godot Resource",
    "Gemini",
    "Diff",
    "Git Attributes",
    "Git Commit",
    "Git Config",
    "Git Ignore",
    "Git Rebase",
    "Gleam",
    "Go Sum",
    "GraphQL",
    "DOT",
    "Gren",
    "Groovy",
    "GROQ",
    "Haml",
    "Hare",
    "Haxe",
    "Helm",
    "HLSL",
    "http",
    "Hurl",
    "iCal",
    "Idris2",
    "IPKG",
    "Inform 6",
    "ini",
    "ISLE",
    "Janet",
    "Java",
    "Properties",
    "Jinja2",
    "Jsonnet",
    "Julia",
    "Just",
    "Kconfig",
    "Kdl",
    "Kotlin",
    "BibTeX",
    "LaTeX",
    "Ledger",
    "LESS",
    "LilyPond",
    "LilyPond Scheme",
    "Liquid",
    "LOG",
    "Lox",
    "Luau",
    "Make",
    "MATLAB",
    "",
    "Move",
    "move",
    "Navi",
    "Navi Stream",
    "CMake",
    "Nginx",
    "Nickel",
    "Nim",
    "Nim Format String",
    "Nix",
    "Noir",
    "Nu",
    "Dune",
    "OCaml Interface",
    "OCaml",
    "Odin",
    "OMNeT++ MSG",
    "OMNeT++ NED",
    "OpenSCAD",
    "Org",
    "Pact",
    "Path of Exile Filter",
    "Perl",
    "Perm",
    "Pest",
    "PHP",
    "PHPDoc",
    "pica200",
    "Pkl",
    "PlantUML",
    "Animation.txt",
    "Pdxinfo",
    "PowerShell",
    "Prisma",
    "Prolog",
    "Pug",
    "QML",
    "QuakeC",
    "R",
    "Racket",
    "Rainbow CSV",
    "Rainbow TSV",
    "RCL",
    "rego",
    "ReScript",
    "Rhai",
    "Roc",
    "RON",
    "RPM Spec",
    "reST",
    "ERB",
    "RBS",
    "Ruby",
    "SageMath",
    "Scala",
    "Scheme",
    "SCSS",
    "Simula",
    "Slim",
    "Smithy",
    "Standard ML",
    "Snakemake",
    "Solidity",
    "Sourcepawn",
    "SQL",
    "SSH Config",
    "Stan",
    "bazelrc",
    "Starlark",
    "Strace",
    "Surreal Query Language",
    "Svelte",
    "Swift",
    "Templ",
    "Tera (CSS)",
    "Tera (HTML)",
    "Tera (JSON)",
    "Tera (TOML)",
    "Tera (YAML)",
    "Tera",
    "tmux",
    "Tree-sitter Query",
    "Twig",
    "Typst",
    "Unison",
    "V",
    "Vala",
    "vCard",
    "Vento",
    "Verilog",
    "VHDL",
    "VHS",
    "VRL",
    "Vue.js",
    "WebAssembly Text Format",
    "WDL",
    "Wgsl",
    "whkd",
    "WIT",
    "XML",
    "Yara",
    "ziggy-schema",
    "ziggy",
    "C",
    "C++",
    "CSS",
    "Go",
    "Go Mod",
    "Go Work",
    "JavaScript",
    "JSDoc",
    "JSON",
    "JSONC",
    "Markdown-Inline",
    "Markdown",
    "Python",
    "Regex",
    "Rust",
    "TSX",
    "TypeScript",
    "YAML",
    "CSharp",
    "Elixir",
    "HEEX",
    "Erlang",
    "GLSL",
    "Haskell",
    "HTML",
    "Lua",
    "Proto",
    "PureScript",
    "HCL",
    "Terraform Vars",
    "Terraform",
    "TOML",
    "Uiua",
    "Zig",
    "edge",
]
