[package]
name = "wakatime-ls"
version.workspace = true
edition = "2021"
repository = "https://github.com/wakatime/zed-wakatime"


[dependencies]
arc-swap = "1.7.1"
chrono = "0.4.41"
clap = "4.5.41"
serde = "1.0.219"
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["full"] }
tower-lsp = "0.20.0"
url = "2.5.4"
